// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: filter/v1/filter_messages.proto

package filterv1

import (
	v1 "github.com/darvenommm/dating-bot-service/pkg/api/common/v1"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gender        v1.Gender              `protobuf:"varint,2,opt,name=gender,proto3,enum=common.v1.Gender" json:"gender,omitempty"`
	MinAge        uint32                 `protobuf:"varint,3,opt,name=min_age,json=minAge,proto3" json:"min_age,omitempty"`
	MaxAge        uint32                 `protobuf:"varint,4,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Location      *latlng.LatLng         `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFilterRequest) Reset() {
	*x = SetFilterRequest{}
	mi := &file_filter_v1_filter_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFilterRequest) ProtoMessage() {}

func (x *SetFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filter_v1_filter_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFilterRequest.ProtoReflect.Descriptor instead.
func (*SetFilterRequest) Descriptor() ([]byte, []int) {
	return file_filter_v1_filter_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SetFilterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetFilterRequest) GetGender() v1.Gender {
	if x != nil {
		return x.Gender
	}
	return v1.Gender(0)
}

func (x *SetFilterRequest) GetMinAge() uint32 {
	if x != nil {
		return x.MinAge
	}
	return 0
}

func (x *SetFilterRequest) GetMaxAge() uint32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *SetFilterRequest) GetLocation() *latlng.LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

type SetFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFilterResponse) Reset() {
	*x = SetFilterResponse{}
	mi := &file_filter_v1_filter_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFilterResponse) ProtoMessage() {}

func (x *SetFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filter_v1_filter_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFilterResponse.ProtoReflect.Descriptor instead.
func (*SetFilterResponse) Descriptor() ([]byte, []int) {
	return file_filter_v1_filter_messages_proto_rawDescGZIP(), []int{1}
}

var File_filter_v1_filter_messages_proto protoreflect.FileDescriptor

const file_filter_v1_filter_messages_proto_rawDesc = "" +
	"\n" +
	"\x1ffilter/v1/filter_messages.proto\x12\tfilter.v1\x1a\x16common/v1/gender.proto\x1a\x18google/type/latlng.proto\"\xb9\x01\n" +
	"\x10SetFilterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12)\n" +
	"\x06gender\x18\x02 \x01(\x0e2\x11.common.v1.GenderR\x06gender\x12\x17\n" +
	"\amin_age\x18\x03 \x01(\rR\x06minAge\x12\x17\n" +
	"\amax_age\x18\x04 \x01(\rR\x06maxAge\x12/\n" +
	"\blocation\x18\x05 \x01(\v2\x13.google.type.LatLngR\blocation\"\x13\n" +
	"\x11SetFilterResponseBEZCgithub.com/darvenommm/dating-bot-service/pkg/api/filter/v1;filterv1b\x06proto3"

var (
	file_filter_v1_filter_messages_proto_rawDescOnce sync.Once
	file_filter_v1_filter_messages_proto_rawDescData []byte
)

func file_filter_v1_filter_messages_proto_rawDescGZIP() []byte {
	file_filter_v1_filter_messages_proto_rawDescOnce.Do(func() {
		file_filter_v1_filter_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filter_v1_filter_messages_proto_rawDesc), len(file_filter_v1_filter_messages_proto_rawDesc)))
	})
	return file_filter_v1_filter_messages_proto_rawDescData
}

var file_filter_v1_filter_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filter_v1_filter_messages_proto_goTypes = []any{
	(*SetFilterRequest)(nil),  // 0: filter.v1.SetFilterRequest
	(*SetFilterResponse)(nil), // 1: filter.v1.SetFilterResponse
	(v1.Gender)(0),            // 2: common.v1.Gender
	(*latlng.LatLng)(nil),     // 3: google.type.LatLng
}
var file_filter_v1_filter_messages_proto_depIdxs = []int32{
	2, // 0: filter.v1.SetFilterRequest.gender:type_name -> common.v1.Gender
	3, // 1: filter.v1.SetFilterRequest.location:type_name -> google.type.LatLng
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_filter_v1_filter_messages_proto_init() }
func file_filter_v1_filter_messages_proto_init() {
	if File_filter_v1_filter_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filter_v1_filter_messages_proto_rawDesc), len(file_filter_v1_filter_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filter_v1_filter_messages_proto_goTypes,
		DependencyIndexes: file_filter_v1_filter_messages_proto_depIdxs,
		MessageInfos:      file_filter_v1_filter_messages_proto_msgTypes,
	}.Build()
	File_filter_v1_filter_messages_proto = out.File
	file_filter_v1_filter_messages_proto_goTypes = nil
	file_filter_v1_filter_messages_proto_depIdxs = nil
}
