// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/gender.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_gender_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_common_v1_gender_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_gender_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_gender_proto protoreflect.FileDescriptor

const file_common_v1_gender_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/gender.proto\x12\tcommon.v1*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02BEZCgithub.com/darvenommm/dating-bot-service/pkg/api/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_gender_proto_rawDescOnce sync.Once
	file_common_v1_gender_proto_rawDescData []byte
)

func file_common_v1_gender_proto_rawDescGZIP() []byte {
	file_common_v1_gender_proto_rawDescOnce.Do(func() {
		file_common_v1_gender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_gender_proto_rawDesc), len(file_common_v1_gender_proto_rawDesc)))
	})
	return file_common_v1_gender_proto_rawDescData
}

var file_common_v1_gender_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_gender_proto_goTypes = []any{
	(Gender)(0), // 0: common.v1.Gender
}
var file_common_v1_gender_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_gender_proto_init() }
func file_common_v1_gender_proto_init() {
	if File_common_v1_gender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_gender_proto_rawDesc), len(file_common_v1_gender_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_gender_proto_goTypes,
		DependencyIndexes: file_common_v1_gender_proto_depIdxs,
		EnumInfos:         file_common_v1_gender_proto_enumTypes,
	}.Build()
	File_common_v1_gender_proto = out.File
	file_common_v1_gender_proto_goTypes = nil
	file_common_v1_gender_proto_depIdxs = nil
}
