// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: profile/v1/profile_service.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_profile_v1_profile_service_proto protoreflect.FileDescriptor

const file_profile_v1_profile_service_proto_rawDesc = "" +
	"\n" +
	" profile/v1/profile_service.proto\x12\n" +
	"profile.v1\x1a!profile/v1/profile_messages.proto2\x8c\x02\n" +
	"\x0eProfileService\x12K\n" +
	"\n" +
	"SetProfile\x12\x1d.profile.v1.SetProfileRequest\x1a\x1e.profile.v1.SetProfileResponse\x12K\n" +
	"\n" +
	"GetProfile\x12\x1d.profile.v1.GetProfileRequest\x1a\x1e.profile.v1.GetProfileResponse\x12`\n" +
	"\x11GetRecommendation\x12$.profile.v1.GetRecommendationRequest\x1a%.profile.v1.GetRecommendationResponseBGZEgithub.com/darvenommm/dating-bot-service/pkg/api/profile/v1;profilev1b\x06proto3"

var file_profile_v1_profile_service_proto_goTypes = []any{
	(*SetProfileRequest)(nil),         // 0: profile.v1.SetProfileRequest
	(*GetProfileRequest)(nil),         // 1: profile.v1.GetProfileRequest
	(*GetRecommendationRequest)(nil),  // 2: profile.v1.GetRecommendationRequest
	(*SetProfileResponse)(nil),        // 3: profile.v1.SetProfileResponse
	(*GetProfileResponse)(nil),        // 4: profile.v1.GetProfileResponse
	(*GetRecommendationResponse)(nil), // 5: profile.v1.GetRecommendationResponse
}
var file_profile_v1_profile_service_proto_depIdxs = []int32{
	0, // 0: profile.v1.ProfileService.SetProfile:input_type -> profile.v1.SetProfileRequest
	1, // 1: profile.v1.ProfileService.GetProfile:input_type -> profile.v1.GetProfileRequest
	2, // 2: profile.v1.ProfileService.GetRecommendation:input_type -> profile.v1.GetRecommendationRequest
	3, // 3: profile.v1.ProfileService.SetProfile:output_type -> profile.v1.SetProfileResponse
	4, // 4: profile.v1.ProfileService.GetProfile:output_type -> profile.v1.GetProfileResponse
	5, // 5: profile.v1.ProfileService.GetRecommendation:output_type -> profile.v1.GetRecommendationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_service_proto_init() }
func file_profile_v1_profile_service_proto_init() {
	if File_profile_v1_profile_service_proto != nil {
		return
	}
	file_profile_v1_profile_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_service_proto_rawDesc), len(file_profile_v1_profile_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_service_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_service_proto_depIdxs,
	}.Build()
	File_profile_v1_profile_service_proto = out.File
	file_profile_v1_profile_service_proto_goTypes = nil
	file_profile_v1_profile_service_proto_depIdxs = nil
}
