// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: profile/v1/profile_messages.proto

package profilev1

import (
	v1 "github.com/darvenommm/dating-bot-service/pkg/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserId        int64                   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                  `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Gender        v1.Gender               `protobuf:"varint,3,opt,name=gender,proto3,enum=common.v1.Gender" json:"gender,omitempty"`
	Age           uint32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Photo         *wrapperspb.BytesValue  `protobuf:"bytes,6,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profile_v1_profile_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Profile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Profile) GetGender() v1.Gender {
	if x != nil {
		return x.Gender
	}
	return v1.Gender(0)
}

func (x *Profile) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Profile) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Profile) GetPhoto() *wrapperspb.BytesValue {
	if x != nil {
		return x.Photo
	}
	return nil
}

type SetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Gender        v1.Gender              `protobuf:"varint,3,opt,name=gender,proto3,enum=common.v1.Gender" json:"gender,omitempty"`
	Age           uint32                 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Photo         []byte                 `protobuf:"bytes,6,opt,name=photo,proto3,oneof" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfileRequest) Reset() {
	*x = SetProfileRequest{}
	mi := &file_profile_v1_profile_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileRequest) ProtoMessage() {}

func (x *SetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileRequest.ProtoReflect.Descriptor instead.
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetProfileRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SetProfileRequest) GetGender() v1.Gender {
	if x != nil {
		return x.Gender
	}
	return v1.Gender(0)
}

func (x *SetProfileRequest) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SetProfileRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *SetProfileRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

type SetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfileResponse) Reset() {
	*x = SetProfileResponse{}
	mi := &file_profile_v1_profile_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileResponse) ProtoMessage() {}

func (x *SetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileResponse.ProtoReflect.Descriptor instead.
func (*SetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_messages_proto_rawDescGZIP(), []int{2}
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_v1_profile_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_v1_profile_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationRequest) Reset() {
	*x = GetRecommendationRequest{}
	mi := &file_profile_v1_profile_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationRequest) ProtoMessage() {}

func (x *GetRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecommendationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetRecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationResponse) Reset() {
	*x = GetRecommendationResponse{}
	mi := &file_profile_v1_profile_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationResponse) ProtoMessage() {}

func (x *GetRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecommendationResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_profile_v1_profile_messages_proto protoreflect.FileDescriptor

const file_profile_v1_profile_messages_proto_rawDesc = "" +
	"\n" +
	"!profile/v1/profile_messages.proto\x12\n" +
	"profile.v1\x1a\x16common/v1/gender.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xef\x01\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12)\n" +
	"\x06gender\x18\x03 \x01(\x0e2\x11.common.v1.GenderR\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\rR\x03age\x12>\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x121\n" +
	"\x05photo\x18\x06 \x01(\v2\x1b.google.protobuf.BytesValueR\x05photo\"\xe2\x01\n" +
	"\x11SetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12)\n" +
	"\x06gender\x18\x03 \x01(\x0e2\x11.common.v1.GenderR\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\rR\x03age\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05photo\x18\x06 \x01(\fH\x01R\x05photo\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_photo\"\x14\n" +
	"\x12SetProfileResponse\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"C\n" +
	"\x12GetProfileResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.profile.v1.ProfileR\aprofile\"3\n" +
	"\x18GetRecommendationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"J\n" +
	"\x19GetRecommendationResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.profile.v1.ProfileR\aprofileBGZEgithub.com/darvenommm/dating-bot-service/pkg/api/profile/v1;profilev1b\x06proto3"

var (
	file_profile_v1_profile_messages_proto_rawDescOnce sync.Once
	file_profile_v1_profile_messages_proto_rawDescData []byte
)

func file_profile_v1_profile_messages_proto_rawDescGZIP() []byte {
	file_profile_v1_profile_messages_proto_rawDescOnce.Do(func() {
		file_profile_v1_profile_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_profile_messages_proto_rawDesc), len(file_profile_v1_profile_messages_proto_rawDesc)))
	})
	return file_profile_v1_profile_messages_proto_rawDescData
}

var file_profile_v1_profile_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_profile_v1_profile_messages_proto_goTypes = []any{
	(*Profile)(nil),                   // 0: profile.v1.Profile
	(*SetProfileRequest)(nil),         // 1: profile.v1.SetProfileRequest
	(*SetProfileResponse)(nil),        // 2: profile.v1.SetProfileResponse
	(*GetProfileRequest)(nil),         // 3: profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),        // 4: profile.v1.GetProfileResponse
	(*GetRecommendationRequest)(nil),  // 5: profile.v1.GetRecommendationRequest
	(*GetRecommendationResponse)(nil), // 6: profile.v1.GetRecommendationResponse
	(v1.Gender)(0),                    // 7: common.v1.Gender
	(*wrapperspb.StringValue)(nil),    // 8: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),     // 9: google.protobuf.BytesValue
}
var file_profile_v1_profile_messages_proto_depIdxs = []int32{
	7, // 0: profile.v1.Profile.gender:type_name -> common.v1.Gender
	8, // 1: profile.v1.Profile.description:type_name -> google.protobuf.StringValue
	9, // 2: profile.v1.Profile.photo:type_name -> google.protobuf.BytesValue
	7, // 3: profile.v1.SetProfileRequest.gender:type_name -> common.v1.Gender
	0, // 4: profile.v1.GetProfileResponse.profile:type_name -> profile.v1.Profile
	0, // 5: profile.v1.GetRecommendationResponse.profile:type_name -> profile.v1.Profile
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_messages_proto_init() }
func file_profile_v1_profile_messages_proto_init() {
	if File_profile_v1_profile_messages_proto != nil {
		return
	}
	file_profile_v1_profile_messages_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_messages_proto_rawDesc), len(file_profile_v1_profile_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_v1_profile_messages_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_messages_proto_depIdxs,
		MessageInfos:      file_profile_v1_profile_messages_proto_msgTypes,
	}.Build()
	File_profile_v1_profile_messages_proto = out.File
	file_profile_v1_profile_messages_proto_goTypes = nil
	file_profile_v1_profile_messages_proto_depIdxs = nil
}
