// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: action/v1/action_messages.proto

package actionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_LIKE        Action = 1
	Action_ACTION_DISLIKE     Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_LIKE",
		2: "ACTION_DISLIKE",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_LIKE":        1,
		"ACTION_DISLIKE":     2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_action_v1_action_messages_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_action_v1_action_messages_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_action_v1_action_messages_proto_rawDescGZIP(), []int{0}
}

type AddActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=action.v1.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddActionRequest) Reset() {
	*x = AddActionRequest{}
	mi := &file_action_v1_action_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActionRequest) ProtoMessage() {}

func (x *AddActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActionRequest.ProtoReflect.Descriptor instead.
func (*AddActionRequest) Descriptor() ([]byte, []int) {
	return file_action_v1_action_messages_proto_rawDescGZIP(), []int{0}
}

func (x *AddActionRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *AddActionRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *AddActionRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

type AddActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddActionResponse) Reset() {
	*x = AddActionResponse{}
	mi := &file_action_v1_action_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActionResponse) ProtoMessage() {}

func (x *AddActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_action_v1_action_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActionResponse.ProtoReflect.Descriptor instead.
func (*AddActionResponse) Descriptor() ([]byte, []int) {
	return file_action_v1_action_messages_proto_rawDescGZIP(), []int{1}
}

var File_action_v1_action_messages_proto protoreflect.FileDescriptor

const file_action_v1_action_messages_proto_rawDesc = "" +
	"\n" +
	"\x1faction/v1/action_messages.proto\x12\taction.v1\"}\n" +
	"\x10AddActionRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12)\n" +
	"\x06action\x18\x03 \x01(\x0e2\x11.action.v1.ActionR\x06action\"\x13\n" +
	"\x11AddActionResponse*E\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vACTION_LIKE\x10\x01\x12\x12\n" +
	"\x0eACTION_DISLIKE\x10\x02BEZCgithub.com/darvenommm/dating-bot-service/pkg/api/action/v1;actionv1b\x06proto3"

var (
	file_action_v1_action_messages_proto_rawDescOnce sync.Once
	file_action_v1_action_messages_proto_rawDescData []byte
)

func file_action_v1_action_messages_proto_rawDescGZIP() []byte {
	file_action_v1_action_messages_proto_rawDescOnce.Do(func() {
		file_action_v1_action_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_v1_action_messages_proto_rawDesc), len(file_action_v1_action_messages_proto_rawDesc)))
	})
	return file_action_v1_action_messages_proto_rawDescData
}

var file_action_v1_action_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_v1_action_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_action_v1_action_messages_proto_goTypes = []any{
	(Action)(0),               // 0: action.v1.Action
	(*AddActionRequest)(nil),  // 1: action.v1.AddActionRequest
	(*AddActionResponse)(nil), // 2: action.v1.AddActionResponse
}
var file_action_v1_action_messages_proto_depIdxs = []int32{
	0, // 0: action.v1.AddActionRequest.action:type_name -> action.v1.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_action_v1_action_messages_proto_init() }
func file_action_v1_action_messages_proto_init() {
	if File_action_v1_action_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_v1_action_messages_proto_rawDesc), len(file_action_v1_action_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_v1_action_messages_proto_goTypes,
		DependencyIndexes: file_action_v1_action_messages_proto_depIdxs,
		EnumInfos:         file_action_v1_action_messages_proto_enumTypes,
		MessageInfos:      file_action_v1_action_messages_proto_msgTypes,
	}.Build()
	File_action_v1_action_messages_proto = out.File
	file_action_v1_action_messages_proto_goTypes = nil
	file_action_v1_action_messages_proto_depIdxs = nil
}
