// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: match/v1/match_messages.proto

package matchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenMatchesRequest) Reset() {
	*x = ListenMatchesRequest{}
	mi := &file_match_v1_match_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenMatchesRequest) ProtoMessage() {}

func (x *ListenMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_match_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenMatchesRequest.ProtoReflect.Descriptor instead.
func (*ListenMatchesRequest) Descriptor() ([]byte, []int) {
	return file_match_v1_match_messages_proto_rawDescGZIP(), []int{0}
}

type ListenMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenMatchesResponse) Reset() {
	*x = ListenMatchesResponse{}
	mi := &file_match_v1_match_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenMatchesResponse) ProtoMessage() {}

func (x *ListenMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_v1_match_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenMatchesResponse.ProtoReflect.Descriptor instead.
func (*ListenMatchesResponse) Descriptor() ([]byte, []int) {
	return file_match_v1_match_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ListenMatchesResponse) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *ListenMatchesResponse) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

var File_match_v1_match_messages_proto protoreflect.FileDescriptor

const file_match_v1_match_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dmatch/v1/match_messages.proto\x12\bmatch.v1\"\x16\n" +
	"\x14ListenMatchesRequest\"W\n" +
	"\x15ListenMatchesResponse\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserIdBCZAgithub.com/darvenommm/dating-bot-service/pkg/api/match/v1;matchv1b\x06proto3"

var (
	file_match_v1_match_messages_proto_rawDescOnce sync.Once
	file_match_v1_match_messages_proto_rawDescData []byte
)

func file_match_v1_match_messages_proto_rawDescGZIP() []byte {
	file_match_v1_match_messages_proto_rawDescOnce.Do(func() {
		file_match_v1_match_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_match_v1_match_messages_proto_rawDesc), len(file_match_v1_match_messages_proto_rawDesc)))
	})
	return file_match_v1_match_messages_proto_rawDescData
}

var file_match_v1_match_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_match_v1_match_messages_proto_goTypes = []any{
	(*ListenMatchesRequest)(nil),  // 0: match.v1.ListenMatchesRequest
	(*ListenMatchesResponse)(nil), // 1: match.v1.ListenMatchesResponse
}
var file_match_v1_match_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_match_v1_match_messages_proto_init() }
func file_match_v1_match_messages_proto_init() {
	if File_match_v1_match_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_v1_match_messages_proto_rawDesc), len(file_match_v1_match_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_match_v1_match_messages_proto_goTypes,
		DependencyIndexes: file_match_v1_match_messages_proto_depIdxs,
		MessageInfos:      file_match_v1_match_messages_proto_msgTypes,
	}.Build()
	File_match_v1_match_messages_proto = out.File
	file_match_v1_match_messages_proto_goTypes = nil
	file_match_v1_match_messages_proto_depIdxs = nil
}
