// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: match/v1/match_service.proto

package matchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_match_v1_match_service_proto protoreflect.FileDescriptor

const file_match_v1_match_service_proto_rawDesc = "" +
	"\n" +
	"\x1cmatch/v1/match_service.proto\x12\bmatch.v1\x1a\x1dmatch/v1/match_messages.proto2b\n" +
	"\fMatchService\x12R\n" +
	"\rListenMatches\x12\x1e.match.v1.ListenMatchesRequest\x1a\x1f.match.v1.ListenMatchesResponse0\x01BCZAgithub.com/darvenommm/dating-bot-service/pkg/api/match/v1;matchv1b\x06proto3"

var file_match_v1_match_service_proto_goTypes = []any{
	(*ListenMatchesRequest)(nil),  // 0: match.v1.ListenMatchesRequest
	(*ListenMatchesResponse)(nil), // 1: match.v1.ListenMatchesResponse
}
var file_match_v1_match_service_proto_depIdxs = []int32{
	0, // 0: match.v1.MatchService.ListenMatches:input_type -> match.v1.ListenMatchesRequest
	1, // 1: match.v1.MatchService.ListenMatches:output_type -> match.v1.ListenMatchesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_match_v1_match_service_proto_init() }
func file_match_v1_match_service_proto_init() {
	if File_match_v1_match_service_proto != nil {
		return
	}
	file_match_v1_match_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_match_v1_match_service_proto_rawDesc), len(file_match_v1_match_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_match_v1_match_service_proto_goTypes,
		DependencyIndexes: file_match_v1_match_service_proto_depIdxs,
	}.Build()
	File_match_v1_match_service_proto = out.File
	file_match_v1_match_service_proto_goTypes = nil
	file_match_v1_match_service_proto_depIdxs = nil
}
